version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing shared dependencies...
      - pip install -r ./lambdas/requirements.txt -t /tmp/dependencies

  pre_build:
    commands:
      - echo Pre-build phase...

  build:
    commands:
      - echo Building the search-photos Lambda function...
      - cd ./lambdas
      - cp -r /tmp/dependencies ./search-photos
      - cd search-photos
      - zip -r9 ../search-photos.zip .
      - cd ..
      - echo Building the index-photos Lambda function...
      - cp -r /tmp/dependencies ./index-photos
      - cd index-photos
      - zip -r9 ../index-photos.zip .
      - cd ..
      - ls -al

  post_build:
    commands:
      - echo Updating code for the search-photos Lambda function...
      - >
        aws lambda update-function-code --function-name search-photos 
        --zip-file fileb://lambdas/search-photos.zip 
      
      - echo Updating code for the index-photos Lambda function...
      - >
        aws lambda update-function-code --function-name index-photos 
        --zip-file fileb://lambdas/index-photos.zip 


artifacts:
  files:
    - lambdas/search-photos.zip
    - lambdas/index-photos.zip
